default:
  index_symbol: NSE:NIFTY 50
  symbol_initials: NIFTY25O14
  pe_gap: 10
  ce_gap: 10
  pe_quantity: 75
  ce_quantity: 75
  pe_symbol_gap: 300
  ce_symbol_gap: 300
  min_price_to_sell: 10
  max_price_to_sell: 30
  sell_multiplier_threshold: 5
  pe_reset_gap: 30
  ce_reset_gap: 30
  pe_start_point: 0
  ce_start_point: 0
  trans_type: SELL
  exchange: NFO
  order_type: MARKET
  product_type: NRML
  stoploss_enabled: true
  stoploss_multiplier: 2
  stoploss_preferred_order_type: SL
  stoploss_fallback_order_type: SL-M
  stoploss_limit_buffer: 1
  stoploss_price_precision: 2
  stoploss_use_quote_for_exec_price: true
  stoploss_tag: SurvivorSL
  stoploss_auto_place: true
  stoploss_retry_attempts: 2
  stoploss_retry_delay_secs: 1
